ci:
  autoupdate_schedule: quarterly
  autofix_prs: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.5.0'
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: check-case-conflict
  - id: fix-encoding-pragma
    args:
    - --remove
  - id: mixed-line-ending
- repo: https://github.com/glotzerlab/fix-license-header
  rev: v0.3.2
  hooks:
  - id: fix-license-header
    name: Fix license headers (Python)
    types_or: [python, cython]
    args:
    - --license-file=LICENSE
    - --add=Part of HOOMD-blue, released under the BSD 3-Clause License.
    - --keep-before=#!
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.2
  hooks:
    - id: ruff-format
    - id: ruff
