name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger on pull requests.
  pull_request:

  # Trigger on pushes to the mainline branches. This prevents building commits twice when the pull
  # request source branch is in the same repository.
  push:
    branches:
      - "trunk"

  # Trigger on request.
  workflow_dispatch:

jobs:
  execute_benchmarks:
    name: Execute benchmarks
    runs-on: ubuntu-latest
    container:
      image: glotzerlab/software:nompi
      options: -u 0
    env:
      benchmark_options: >
        --device CPU
        -N 4000
        -v
        --warmup_steps 1000
        --benchmark_steps 1000
    steps:
    - uses: actions/checkout@v4.1.1
    - name: List benchmarks
      run: ls **/*.py
    - name: Cache configurations
      uses: actions/cache@v3.3.2
      with:
        path: initial_configuration_cache
        key: ${{ env.benchmark_options }}
    - name: Execute all benchmarks
      run: >
        python3 -u -m hoomd_benchmarks ${benchmark_options}
    - name: Execute hpmc_sphere
      run: python3 -u -m hoomd_benchmarks.hpmc_sphere ${benchmark_options}
    - name: Execute md_pair_lj
      run: python3 -u -m hoomd_benchmarks.md_pair_lj ${benchmark_options}
    - name: Execute md_pair_wca
      run: python3 -u -m hoomd_benchmarks.md_pair_wca ${benchmark_options}
