name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

  push:
    branches:
      - "trunk"

  workflow_dispatch:

jobs:
  execute_benchmarks:
    name: Execute benchmarks
    runs-on: ubuntu-24.04
    env:
      benchmark_options: >
        --device CPU
        -N 4000
        -v
        --warmup_steps 1000
        --benchmark_steps 1000
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Create Python Environment
      uses: mamba-org/setup-micromamba@f8b8a1e23a26f60a44c853292711bacfd3eac822 # v1.9.0
      with:
        micromamba-version: '1.5.8-0'
        environment-name: test
        environment-file: .github/workflows/environments/py312-conda-lock.yml
        micromamba-root-path: ${{ github.workspace }}/micromamba

    - name: Configure conda environment variables
      run: |
        echo "$MAMBA_ROOT_PREFIX/envs/test/bin" >> $GITHUB_PATH
    - name: List benchmarks
      run: ls **/*.py
    - name: Cache configurations
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: initial_configuration_cache
        key: ${{ env.benchmark_options }}
    - name: Execute all benchmarks
      run: >
        python3 -u -m hoomd_benchmarks ${benchmark_options}
    - name: Execute hpmc_sphere
      run: python3 -u -m hoomd_benchmarks.hpmc_sphere ${benchmark_options}
    - name: Execute md_pair_lj
      run: python3 -u -m hoomd_benchmarks.md_pair_lj ${benchmark_options}
    - name: Execute md_pair_wca
      run: python3 -u -m hoomd_benchmarks.md_pair_wca ${benchmark_options}
