name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

  push:
    branches:
      - "trunk"

  workflow_dispatch:

jobs:
  execute_benchmarks:
    name: Execute benchmarks
    runs-on: ubuntu-24.04
    env:
      benchmark_options: >
        --device CPU
        -N 4000
        -v
        --warmup_steps 1000
        --benchmark_steps 1000
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Create Python Environment
      uses: mamba-org/setup-micromamba@b09ef9b599704322748535812ca03efb2625677b # v2.0.5
      with:
        micromamba-version: '2.0.2-2'
        environment-name: test
        environment-file: .github/workflows/environments/py312-conda-lock.yml
        micromamba-root-path: ${{ github.workspace }}/micromamba

    - name: Configure conda environment variables
      run: |
        echo "$MAMBA_ROOT_PREFIX/envs/test/bin" >> $GITHUB_PATH
    - name: List benchmarks
      run: ls **/*.py
    - name: Cache configurations
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: initial_configuration_cache
        key: ${{ env.benchmark_options }}
    - name: Execute all benchmarks
      run: >
        python3 -u -m hoomd_benchmarks ${benchmark_options}
    - name: Execute hpmc_sphere
      run: python3 -u -m hoomd_benchmarks.hpmc_sphere ${benchmark_options}
    - name: Execute md_pair_lj
      run: python3 -u -m hoomd_benchmarks.md_pair_lj ${benchmark_options}
    - name: Execute md_pair_wca
      run: python3 -u -m hoomd_benchmarks.md_pair_wca ${benchmark_options}
