name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger on pull requests.
  pull_request:

  # Trigger on pushes to the mainline branches. This prevents building commits twice when the pull
  # request source branch is in the same repository.
  push:
    branches:
      - "trunk"

  # Trigger on request.
  workflow_dispatch:

jobs:
  execute_benchmarks:
    name: Execute benchmarks
    runs-on: ubuntu-latest
    container:
      image: glotzerlab/software:beta-nompi
      options: -u 0
    steps:
    # clone the benchmarks and run them
    - uses: actions/checkout@v2.3.4
    - name: List benchmarks
      run: ls **/*.py
    # Cache the generated initial configurations. The cache key must reflect the command line
    # options provided to the benchmarks below.
    - name: Cache configurations
      uses: actions/cache@v2.1.6
      with:
        path: initial_configuration_cache
        key: N-4000-rho-default
    - name: Execute benchmarks
      run: python3 -m hoomd_benchmarks --device CPU -N 4000 -v
